// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlidEagle.Data;

#nullable disable

namespace SlidEagle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230319154117_RideStyleCreate")]
    partial class RideStyleCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlidEagle.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RideStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RideStyleId")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("RideStyleId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SlidEagle.Models.RideStyle", b =>
                {
                    b.Property<int>("RideStyleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RideStyleId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RideStyleId");

                    b.ToTable("RideStyles");
                });

            modelBuilder.Entity("SlidEagle.Models.Item", b =>
                {
                    b.HasOne("SlidEagle.Models.RideStyle", null)
                        .WithMany("Items")
                        .HasForeignKey("RideStyleId");
                });

            modelBuilder.Entity("SlidEagle.Models.RideStyle", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
